Axi test harness
cucapra/calyx pull request #1153
Opened 2022-08-22 03:58 UTC by nathanielnrn

Thought it would be useful to open a draft PR to allow time to get feedback  while classes are starting and I'm less available. This is nearly done.

Pull request allows for runt testing of cocotb simulation which outputs the execution of a kernel based on [`examples/dahlia`](https://github.com/cucapra/calyx/tree/master/examples/dahlia) `.data` and `.expected` files.
Also introduces a subdirectory specifically for cocotb tests.

DRAFT: Regarding the reason this is a draft. Currently, running the make commands from [runt](https://github.com/cucapra/calyx/blob/aa305195a2e3e5b59c54766dcdba71aec77df5fa/runt.toml#L291-L299) does not behave the same way as running each command from a single shell one by one. Specifically, the Makefile does not use a new `toplevel.v` in spite of the `-B` flag. This means that a single computation (i.e dot-product) is performed on all data (i.e vectorized add data).

Additionally, make outputs some text which is specific to the file system running the command. For example, make outputs the commands it performs. Is there a way to selectively gather this text within runt? Just adding some `tail` and `head` commands to our output in the `rust.toml`?

2022-08-22 06:46 UTC, rachitnigam commented on fpga/test-harness/hdl/vadd/main.sv
> +/**
Does this file need to be committed? Seems like it is generated from Calyx

2022-08-22 06:47 UTC, rachitnigam commented on fpga/test-harness/hdl/vadd/toplevel.v
> +`default_nettype none
Is this a generated file?

2022-08-22 06:47 UTC, rachitnigam commented on runt.toml
> +  "tests/"
Not sure why there is extra `tests/` folder here

2022-09-11 23:30 UTC, nathanielnrn commented on fpga/test-harness/hdl/vadd/toplevel.v
> +`default_nettype none
Currently cocotb expects to receive verilog files on which to simulate. Do these exist somewhere else I can symlink to? Should this be handled some other way?

2022-09-11 23:42 UTC, nathanielnrn commented
Currently changing this to only test a single calyx program: vectorized-add. I think one test is better than no test, and runt behaves strangely when supplied more than one [directory](https://github.com/cucapra/calyx/pull/1153/files#diff-4de5114f2b8940b402eab836491023d894ceb8854235d1dda559364646b82aeaR293).

(It doesn't seem to fetch the correct toplevel, but will perform same computation on different input data, i.e dot product on vadd data).

Additionally, I am getting this weird unclosed file error which is polluting runt's expected output. As soon as that is fixed, this should be ready for deployment.

2022-09-12 21:59 UTC, rachitnigam commented
The unclosed file error is sadly expected. It is a problem with cocotb and they haven’t fixed it

2022-09-12 21:59 UTC, rachitnigam commented
hmm, runt should correctly work with multiple directories. Not sure why it’s failing to do thag

2022-09-12 22:00 UTC, rachitnigam commented
Can you try changing the runt command to cd into the directory and run make from there?

2022-10-02 03:11 UTC, nathanielnrn commented
So (finally!) had some time to fix this! Apologies for taking so long. I believe the most recent push should fix the one-computation-kernel issue

2022-10-03 18:43 UTC, rachitnigam commented
@nathanielnrn seems like the tests are failing?

2022-10-05 17:36 UTC, nathanielnrn commented
> @nathanielnrn seems like the tests are failing?

Has to do with the AxBurst ports I added to make cocotb happy, probably should have made another branch for this. Updated runt gold files fixes this.

2022-10-05 19:11 UTC, rachitnigam commented
Hm, still seems to be failing

2022-10-21 23:57 UTC, rachitnigam commented
Looks like everything is passing @nathanielnrn! Merge when ready!

2022-10-21 23:58 UTC, rachitnigam requested changes
Actually I noticed there is a really big `.sv` file we're committing. Is that intentional?

2022-10-23 00:37 UTC, nathanielnrn commented
Latest commit makes the `toplevel.v` and `main.sv` we use for `cocotb` be dynamically generated as expected. However, the runt tests we have aren't passing due to differences in a newline here and lack of a new line there. I'm not able to reproduce failing cases on locally built docker containers.
Any thoughts from anyone by any chance? I'll keeping looking into it in the mean time.

2022-10-25 22:28 UTC, sampsyo commented
Neat! Hella weird about the newline nonsense. I guess I suspect some vagary about the test's shell pipeline…

May I recommend using `fud -v` or whatever it is to get verbose output from Fud instead of that progress indicator thingy ⠋⠙?

2022-10-25 23:14 UTC, rachitnigam commented
Usually we use `-q` with `fud` in tests to make it stop producing any execution related output

2022-12-21 13:20 UTC, rachitnigam commented
Okay, my changes should fix the silly `fud` problem @nathanielnrn was running into. Once this is merged, we should check off tasks in #1104 and create a new issue to turn the `cocotb` hackery embedded in the `runt` commands into a `fud` stage so we can start running lots of different Calyx kernels with this harness

2023-01-01 04:40 UTC, rachitnigam commented
@nathanielnrn if you'd like, feel free to press the big green button! Congratulations on a successful summer research project!

2023-01-01 08:40 UTC, merged