Compile sync with fsm
cucapra/calyx pull request #1359
Opened 2023-02-13 18:56 UTC by paili0628

2023-02-16 18:35 UTC, rachitnigam commented on calyx/src/passes/compile_sync_without_sync_reg.rs
> +        "compile-sync-without-sync-reg"
This name is a little cumbersome. Since this is a default pass, can we call it `compile-sync` and other one as `compile-sync-with-sync-reg`?

2023-02-16 18:35 UTC, rachitnigam commented on calyx/src/passes/compile_sync_without_sync_reg.rs
> +    fn get_reg(&mut self, idx: &u64) -> &mut RRC<ir::Cell>;
Please document the trait and the functions

2023-02-16 18:35 UTC, rachitnigam commented on calyx/src/passes/compile_sync_without_sync_reg.rs
> +type BarrierMap = HashMap<u64, (RRC<ir::Cell>, Box<ir::Guard>)>;
Document the type and what it is used for

2023-02-16 18:36 UTC, rachitnigam requested changes
The code is very light on documentation so I can't really tell what's going on. Can you add some documentation explaining what the pass is trying to achieve, how it interacts with `tdcc` and what the various parts of the code do? 

Once done, I can review again

2023-03-01 06:59 UTC, rachitnigam commented
@paili0628 is there something blocking this PR?

2023-03-01 07:01 UTC, paili0628 commented
Yes, there seems to be a problem with while loops that I am trying to resolve

2023-04-19 01:49 UTC, rachitnigam commented
@paili0628 you mentioned this is working now? Can you push your changes so we can merge?

2023-04-19 02:23 UTC, closed without merging

2023-04-19 02:28 UTC, paili0628 commented
I am going to close this branch because I do not want to create confusion. The changes I made does not involve the fsm.